import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Puritan } from "next/font/google";
import "./globals.css";
import { UserInfoProvider } from "@/components/zustandProvider";
import type { AppProps } from "next/app"
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const puritan = Puritan({
  weight: ['400', '700'], // Regular and Bold
  style: ['normal', 'italic'], // Normal and Italic
  subsets: ['latin'],
  variable: '--font-puritan', // CSS variable for native/Tailwind usage
  display: 'swap',
});

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'], // Specify weights you need
  subsets: ["latin"],
  display: "swap", // Optional: improves loading perception
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${puritan.variable} ${roboto .variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
        <UserInfoProvider>
          {children}
          <Toaster position="bottom-right" richColors/>
        
        </UserInfoProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
